---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint & Test Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:

###############
# Set the Job #
###############
jobs:
  lint:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper 
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper 
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: |
          version="${GITHUB_REF##*/}"
          echo "::set-output name=VERSION::${version}"
          echo "::set-output name=month::$(date +'%b')"

      - name: Cache west modules
        uses: actions/cache@v3.0.2
        id: cache
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            .west/
            bootloader/
            ~/.cache/pip
            ~/.local/bin
          key: 1-${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.get_version.outputs.month }}
        timeout-minutes: 5
        continue-on-error: true

      - name: Initialize workspace (west init)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          west init --mr v2.7.0
          west update
          west zephyr-export

      - name: Initialize PIP
        run: |
          apt update
          apt -y install valgrind python3-pip
          pip3 install --user -r zephyr/scripts/requirements.txt
          # pip3 install ValgrindCI
      - name: ZTests
        run: |
          zephyr/scripts/twister -T tests/ -i -v --board-root boards/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: zTest Results
          path: twister-out/twister_report.xml

  publish-test-results:
    name: "Publish Tests Results"
    needs: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"
          comment_mode: always
